name = "Animal Well"
home = "https://discord.com/channels/731205301247803413/1238463626344665119"
default_url = "https://github.com/ScipioWright/Archipelago-SW/releases/download/{{version}}/animal_well.apworld"

[versions]
"0.3.0" = {}
