name = "Archipela-Go!"
home = "https://discord.com/channels/731205301247803413/1203890996794884126"
default_url = "https://github.com/aki665/react-native-archipelago/releases/download/{{version}}/apgo.apworld"

[versions]
"0.5.0" = {}
