name = "DORONKO WANKO"
home = "https://discord.com/channels/731205301247803413/1325915019313152097"
default_url = "https://github.com/Vendily/DoronkoWankoArchipelago/releases/download/{{version}}/doronko_wanko.apworld"

[versions]
"0.3.0" = {}
