name = "EarthBound"
home = "https://discord.com/channels/731205301247803413/1077266688657068032"

[versions]
"2.0.2" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/earthboundap2.0.2/earthbound.apworld" }
