name = "Ender Lilies"
home = "https://discord.com/channels/731205301247803413/1093030832886792242"

[versions]
"0.7.0" = { url = "https://github.com/Trexounay/EnderLilies.Archipelago/releases/download/v0.7/enderlilies.apworld" }

