name = "Jak and Daxter The Precursor Legacy"
home = "https://discord.com/channels/731205301247803413/1138467653552451606"

[versions]
"0.4.0" = { url = "https://github.com/ArchipelaGOAL/Archipelago/releases/download/beta-v0.4.0/jakanddaxter.apworld" }
"0.4.1" = { url = "https://github.com/ArchipelaGOAL/Archipelago/releases/download/beta-v0.4.1/jakanddaxter.apworld" }
