name = "Keep Talking and Nobody Explodes"
home = "https://discord.com/channels/731205301247803413/1058549067107532840"

[versions]
"0.1.3-a" = { url = "https://github.com/GreenPower713/Archipelago/releases/download/v0.1.3a/ktane.apworld" }
