name = "Manual: Pokemon Snap (N64)"
home = "https://discord.com/channels/1097532591650910289/1231737689951178773"
default_url = "https://github.com/AliRobotnik/PokemonSnap-Archipelago-Manual/releases/download/V{{version}}/manual_pokemonsnap_alirobotnik.apworld"

[versions]
"1.3.1" = {}
