name = "Mega Man X"
home = "https://discord.com/channels/731205301247803413/1134349743984742520"
default_url = "https://github.com/TheLX5/Archipelago/releases/download/mmx-v{{version}}/mmx.apworld"

[versions]
"1.4.0" = {}
