name = "Monster Sanctuary"
home = "https://discord.com/channels/731205301247803413/1217944663864901632"
default_url = "https://github.com/Gtaray/archipelago-monstersanctuary/releases/download/v{{version}}/monster_sanctuary.apworld"

[versions]
"1.1.4" = {}
