name = "Paper Mario"
home = "https://discord.com/channels/731205301247803413/1059875783071502398"
default_url = "https://github.com/JKBSunshine/PMR_APWorld/releases/download/v{{version}}/papermario.apworld"

[versions]
"0.4.1" = {}
"0.4.2" = {}
"0.4.4" = {}
# They pushed over the apworld at least once after inclusion in the index
"0.5.0+hotfix1" = { url = "https://github.com/JKBSunshine/PMR_APWorld/releases/download/v0.5.0/papermario.apworld" }
