name = "Pokemon FireRed and LeafGreen"
home = "https://discord.com/channels/731205301247803413/1232325933902467082"
default_url = "https://github.com/vyneras/Archipelago/releases/download/{{version}}/pokemon_frlg.apworld"

[versions]
"0.6.0-beta" = {}
