name = "Reventure"
home = "https://discord.com/channels/731205301247803413/1200081144629174363"
default_url = "https://github.com/Droppel/ReventureEndingRando/releases/download/{{version}}/reventure.apworld"

[versions]
"0.12.1" = {}
