name = "Sonic Adventure DX"
home = "https://discord.com/channels/731205301247803413/1183347590981505075"
default_url = "https://github.com/ClassicSpeed/sadx-classic-randomizer/releases/download/v{{version}}/sadx.apworld"

[versions]
"0.8.4" = {}
