name = "Spelunky 2"
home = "https://discord.com/channels/731205301247803413/1142626744629735555"
default_url = "https://github.com/Eszenn/Spelunky-2-Archipelago/releases/download/Spelunky2v{{version}}/spelunky2.apworld"

[versions]
"0.1.0" = {}
