name = "ToeJam and Earl"
home = "https://discord.com/channels/731205301247803413/1204326236415856671"
default_url = "https://github.com/IgnisUmbrae/TJE-Archipelago/releases/download/v{{version}}/tje.apworld"

[versions]
"0.1.3" = {}
