name = "Void Stranger"
home = "https://discord.com/channels/731205301247803413/1231073014439743528"
default_url = "https://github.com/CriminalPancake/void-stranger-ap/raw/refs/tags/v{{version}}/voidstranger.apworld"

[versions]
"0.8.0" = {}

